### ISSUE TITLE
Block execution at the chain tip

### ISSUE THREAD

**Issue by canepat** [erigontech/silkworm#2059]
One missing feature in Erigon++ wrt Erigon2 is the capability to run the block execution at the chain tip.

This is the main tracking issue. Individual issues are listed below:

- [x] #2057
- [x] current result of our analysis for best Cgo cutting point: `ForkValidator` C++ implementation exposed through C API + `EthereumExecutionModule` sibling in silkworm-go calling into it
- [x] #2112
- [x] #2058
- [x] https://github.com/erigontech/silkworm-go/issues/7
- [ ] integrate Silkworm ForkValidator in Erigon2
- [x] #2067
