### ISSUE TITLE
rpcdaemon: state access using temporal KV

### ISSUE THREAD

**Issue by canepat** [erigontech/silkworm#2074]
One of the main features of Erigon3 is moving the entire state content and proof (i.e. account/storage/code/commitment) to snapshot files. This change is also associated with an extension of the `KV` internal gRPC interface, named [temporal KV](https://github.com/ledgerwatch/interfaces/blob/master/remote/kv.proto#L58).
It becomes natural using such `temporal KV` as a basis for porting our RPCDaemon module into the Erigon3 realm: first of all, implementing the out-of-process access, then switching to the embedded in-process version (this will require full support for Erigon3 snapshots).

This is the main tracking issue. Individual issues are listed below:

- [x] #2024
- [x] #2026
- [x] #2068
- [x] state access refactoring #2084 #2100 #2104 #2116 #2129
- [x] transaction/cursor hierarchy refactoring #2098 #2125 #2136 #2175
- [x] state changes stream on generic KV API #2168 
- [x] paginated temporal KV API (domain/history/index) #2186 #2189 #2198 #2202 #2207 #2210 
- [x] implement state access V3 (`StateReader`, `AsyncRemoteState`) with temporal KV API (domain/history/index) #2251 #2253
