### ISSUE TITLE
Block execution over state snapshots

### ISSUE THREAD

**Issue by canepat** [erigontech/silkworm#2313]
One of the main features of Erigon3 is moving most of the state content (i.e. account/storage/code) and its validity proof (i.e. commitment) to snapshot flat files. This architectural change requires deep modifications also to the data model in the database (e.g. state history indexing) and to the execution staged pipeline.

This is the main tracking issue. Individual issues are listed below:

- [ ] #2312
- [ ] new state data model in MDBX
- [ ] transaction-level state history granularity
- [ ] collapse execution and post-execution stages in staged pipeline
- [ ] in-process Temporal API endpoints (local)
- [ ] out-of-process Temporal API endpoints (remote)
